import { ProblemStatement } from "../models/ProblemStatement.js";

const problemStatementsData = [
  {
    slug: "securemailscope-ai-assisted-cryptographic-security-posture-assessment",
    title: "SecureMailScope: AI-Assisted Cryptographic Security Posture Assessment for Secure Email Communications",
    organization: "National Technical Research Organisation (NTRO)",
    department: "National Technical Research Organisation (NTRO)",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Email Security / Enterprise Security",
    scope: "Cryptographic Security Assessment / Email Security / Network Forensics / TLS Analysis",
    platformTech: "AI/ML, NLP, Network Forensics, PCAP Analysis, SMTP, IMAP, POP3, TLS, STARTTLS, TCP Stream Reconstruction, X.509 Certificates, Cryptographic Analysis, Explainable AI, JSON/PDF/HTML Reporting",
    description: "Develop an AI-assisted passive network forensic framework that analyzes captured SMTP, IMAP, and POP3 traffic from PCAP files to automatically assess the cryptographic security posture of enterprise email infrastructures. The system should identify email protocols and STARTTLS negotiations, reconstruct TCP communication streams and TLS handshakes, extract and validate X.509 certificates, and identify negotiated TLS versions, cipher suites, key-exchange mechanisms, and other cryptographic characteristics. It should detect deprecated protocols, weak cryptographic algorithms, insecure configurations, certificate vulnerabilities, and Forward Secrecy issues. AI/ML techniques should be used for cryptographic risk classification, anomalous TLS behavior detection, security posture scoring, threat prioritization, and mitigation recommendations. The platform should provide comprehensive forensic reports and an interactive security-analysis dashboard.",
    keyDeliverables: [
      "Automatic SMTP, IMAP, and POP3 protocol identification",
      "STARTTLS negotiation detection and validation",
      "TCP communication stream reconstruction",
      "TLS handshake reconstruction",
      "TLS version identification",
      "Cipher-suite identification",
      "Key-exchange mechanism identification",
      "X.509 certificate extraction",
      "Certificate-chain validation",
      "Certificate expiration analysis",
      "Public-key algorithm and key-length analysis",
      "Digital-signature algorithm identification",
      "Weak cryptographic algorithm detection",
      "Deprecated TLS version detection",
      "Insecure protocol configuration detection",
      "Forward Secrecy assessment",
      "AI-based cryptographic risk scoring",
      "AI-assisted anomalous TLS-session detection",
      "Prioritized security findings",
      "Overall cryptographic security posture assessment",
      "Security mitigation recommendations",
      "JSON, PDF, and HTML forensic reports",
      "Interactive security monitoring and analysis dashboard"
    ],
    sortOrder: 1
  },
  {
    slug: "ai-powered-ipsec-vpn-protocol-analyzer-and-security-assessment-framework",
    title: "AI-Powered IPsec VPN Protocol Analyzer and Security Assessment Framework",
    organization: "National Technical Research Organisation (NTRO)",
    department: "National Technical Research Organisation (NTRO)",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Network Security / VPN Security",
    scope: "IPsec VPN Analysis / Protocol Identification / Cryptographic Security Assessment / Network Traffic Analysis",
    platformTech: "AI/ML, IPsec, IKE, ESP, AH, Network Traffic Analysis, PCAP, Wireshark, tcpdump, Cryptographic Analysis, Security Assessment, Explainable AI, Data Visualization, Web Dashboard",
    description: "Design and develop an AI-driven platform for automatically analyzing IPsec VPN deployments under different security configurations. The platform should analyze captured traffic or live network streams, identify IPsec and IKE characteristics, infer Tunnel or Transport mode, identify encryption, authentication and key-exchange configurations, and assess the overall security posture.\n\nThe solution should support a VPN testbed with configurations such as AES-128/256, AES-GCM, AES-CBC + HMAC, different DH groups, PFS enabled/disabled, IPv4/IPv6 and different traffic types. It should capture IKE, ESP, optional AH and normal communication traffic, use AI to identify protocol and Security Association characteristics, infer traffic types inside ESP, and evaluate cryptographic strength, compliance, key lifetime, replay protection, PFS, cipher strength and metadata exposure.\n\nThe platform should generate comprehensive security assessments including risk scoring, threat matrices, AI confidence scores, traffic analysis, metadata inference, and executive/technical reports through an interactive dashboard.",
    keyDeliverables: [
      "Working AI-powered IPsec VPN analysis prototype",
      "VPN testbed supporting multiple IPsec security configurations",
      "Traffic capture and dataset preparation for IKE, ESP, AH and normal traffic",
      "AI classification engine for IPsec/IKE protocol and configuration identification",
      "Tunnel/Transport mode and cryptographic configuration identification",
      "ESP traffic-type prediction",
      "Automated cryptographic and configuration security assessment",
      "Risk score, threat matrix and AI confidence score",
      "Interactive security assessment dashboard",
      "Executive and technical security reports",
      "Training/testing dataset",
      "Demonstration video",
      "Technical documentation"
    ],
    sortOrder: 2
  },
  {
    slug: "post-quantum-cryptography-risk-assessment-and-cbom-analytics-tool",
    title: "Post-Quantum Cryptography Risk Assessment and CBOM Analytics Tool",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Cryptographic Security / Enterprise Security",
    scope: "Post-Quantum Cryptography / Cryptographic Bill of Materials (CBOM) / Quantum Risk Assessment / Cryptographic Asset Discovery",
    platformTech: "AI/ML, Cryptographic Analysis, CBOM, Source Code Analysis, Binary Analysis, Software Composition Analysis, Container Security, Risk Assessment, PQC, Hybrid Cryptography, Data Visualization, Web Dashboard",
    description: "Develop a comprehensive Cryptographic Bill of Materials (CBOM) analytics platform to support organizations in preparing for the transition to Post-Quantum Cryptography (PQC). The tool should discover and catalogue cryptographic artefacts—including algorithms, keys, certificates, protocols, libraries, hardware modules and cloud services—across internal and externally facing applications, products and infrastructure.\n\nThe platform should perform quantum risk assessment to identify systems potentially vulnerable to quantum attacks and highlight risks to sensitive data. It should classify cryptographic artefacts based on type, lifetime and business criticality, and apply structured risk frameworks such as Mosca's algorithm by comparing data lifetime and migration time against the expected arrival of cryptographically relevant quantum computers.\n\nBased on the identified risk profile, the tool should recommend suitable PQC or hybrid cryptographic alternatives considering factors such as risk, latency and cost.",
    keyDeliverables: [
      "Comprehensive CBOM analytics tool",
      "Scanning of source-code repositories, binaries, libraries and container images",
      "Discovery and catalogue of cryptographic artefacts",
      "Standardized inventory of cryptographic assets, versions and modes",
      "Quantum-risk assessment and sensitive-data risk identification",
      "Classification based on artefact type, lifetime and business criticality",
      "Mosca-based quantum risk categorization",
      "PQC and hybrid-algorithm recommendations based on risk, latency and cost",
      "Interactive GUI for scan results, cryptographic assets and risk visualization",
      "Comprehensive cryptographic risk and CBOM report"
    ],
    sortOrder: 3
  },
  {
    slug: "enterprise-cryptographic-discovery-and-analysis-tool-ecdat",
    title: "Enterprise Cryptographic Discovery & Analysis Tool (ECDAT)",
    organization: "National Technical Research Organisation (NTRO)",
    department: "National Technical Research Organisation (NTRO)",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Cryptographic Security / Enterprise Security",
    scope: "Cryptographic Discovery / CBOM / Post-Quantum Readiness / Quantum Risk Assessment",
    platformTech: "AI/ML, Cryptographic Analysis, CBOM, Source Code Analysis, Binary Analysis, Library Analysis, Container Security, PQC, Hybrid Cryptography, Risk Assessment, Data Visualization, Web Dashboard",
    description: "Develop an Enterprise Cryptographic Discovery & Analysis Tool (ECDAT) to support organizations transitioning to Post-Quantum Cryptography (PQC). The solution should discover and catalogue cryptographic artefacts—including algorithms, keys, certificates, protocols, libraries, hardware modules and cloud services—across internal and externally facing applications, products and infrastructure.\n\nThe tool should perform comprehensive quantum risk assessment, identify systems potentially vulnerable to quantum attacks, and highlight risks to sensitive data. It should classify cryptographic artefacts based on type, lifetime and business criticality and apply structured frameworks such as Mosca's algorithm by comparing data lifetime and migration time against the expected arrival of cryptographically relevant quantum computers.\n\nThe solution should also recommend suitable PQC or hybrid cryptographic alternatives based on factors such as risk profile, latency and cost. It should scan source-code repositories, binaries, libraries and container images and provide standardized reports and an interactive GUI for visualizing cryptographic assets, risks and analysis results.",
    keyDeliverables: [
      "Comprehensive CBOM analytics tool",
      "Scanning of source-code repositories, binaries, libraries and container images",
      "Discovery and catalogue of cryptographic artefacts",
      "Standardized inventory of cryptographic assets, versions and modes",
      "Quantum risk assessment and sensitive-data risk identification",
      "Classification by artefact type, lifetime and business criticality",
      "Mosca's algorithm-based risk categorization",
      "PQC and hybrid-algorithm recommendations",
      "Risk analysis considering latency and cost",
      "Interactive GUI for scan results and risk visualization",
      "Comprehensive cryptographic asset and risk reports"
    ],
    sortOrder: 4
  },
  {
    slug: "automated-blockchain-intelligence-and-vasp-attribution-engine",
    title: "Automated Blockchain Intelligence & VASP Attribution Engine",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Financial Security / Blockchain / Law Enforcement",
    scope: "Blockchain Intelligence / VASP Attribution / Cryptocurrency Investigation / Multi-Chain Transaction Analysis",
    platformTech: "Agentic AI, Blockchain Analytics, Graph Analytics, AI/ML, Multi-Chain Analysis, API Integration, Transaction Tracing, Risk Scoring, Data Visualization, Web Dashboard",
    description: "Develop an Automated Blockchain Intelligence & VASP Attribution Engine integrated with the SAHYOG Portal through APIs to help Law Enforcement Agencies identify the Virtual Asset Service Provider (VASP) associated with suspect cryptocurrency wallets.\n\nThe system should automatically analyze suspect wallet addresses and trace blockchain transaction paths to identify the nearest centralized exchange, custodial wallet service, or VASP receiving direct deposits. It should support multiple blockchain networks including Bitcoin, Ethereum, Tron, BNB Chain, Solana and Polygon, along with other major chains.\n\nThe platform should identify and classify exchange clusters, hot wallets, deposit wallets, mixers/tumblers, DeFi bridges and cross-chain swap services. It should integrate blockchain intelligence APIs and graph analytics, provide automated VASP tagging and confidence scoring, visualize fund movement and cross-chain transactions, identify laundering typologies, and generate investigation-ready reports.\n\nThe system should also assist investigators in routing lawful disclosure or asset-freezing requests to the appropriate VASP through the SAHYOG Portal.",
    keyDeliverables: [
      "Automated identification of nearest VASP/exchange associated with unknown wallets",
      "API-driven blockchain tracing and attribution",
      "Multi-chain transaction analysis across major blockchain networks",
      "Exchange, deposit-wallet and custodial-wallet identification",
      "Detection/classification of mixers, tumblers, DeFi bridges and cross-chain services",
      "Blockchain transaction and fund-flow visualization",
      "Automated VASP tagging with confidence scores",
      "Wallet and transaction-flow risk classification",
      "Identification of relevant laundering typologies and high-risk wallets",
      "SAHYOG Portal API integration",
      "Investigation-ready reports for LEAs",
      "Case-based analytics dashboard",
      "Automated routing support for lawful disclosure/freezing requests",
      "Scalable architecture for large-volume blockchain transaction analysis"
    ],
    sortOrder: 5
  },
  {
    slug: "automated-attribution-of-unknown-cryptocurrency-wallets-to-nearest-vasps",
    title: "Automated Attribution of Unknown Cryptocurrency Wallets to Nearest Virtual Asset Service Providers (VASPs) through Blockchain Intelligence APIs",
    organization: "Ministry of Home Affairs",
    department: "Indian Cyber Crime Coordination Centre (I4C), CIS Division",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Financial Security / Blockchain / Law Enforcement",
    scope: "Blockchain Intelligence / VASP Attribution / Cryptocurrency Investigation / Multi-Chain Transaction Analysis",
    platformTech: "AI/ML, Blockchain Analytics, Graph Analytics, AI/ML, Blockchain Intelligence APIs, Multi-Chain Analysis, Transaction Tracing, Risk Scoring, Data Visualization, Web Dashboard",
    description: "Develop an Automated Blockchain Intelligence & VASP Attribution Engine integrated with the SAHYOG Portal through APIs to help Law Enforcement Agencies identify the Virtual Asset Service Provider (VASP) associated with unknown or unhosted cryptocurrency wallets.\n\nThe system should automatically analyze suspect cryptocurrency wallet addresses and trace blockchain transaction paths to identify the nearest centralized exchange, custodial wallet service, or VASP receiving direct deposits. It should support multiple blockchain networks including Bitcoin, Ethereum, Tron, BNB Chain, Solana and Polygon, along with other major chains.\n\nThe platform should identify exchange clusters, hot wallets, deposit wallets, mixers/tumblers, DeFi bridges and cross-chain swap services. It should integrate blockchain intelligence APIs and graph analytics engines, provide automated VASP tagging and confidence scoring, visualize fund movement and cross-chain transactions, identify laundering typologies, and generate investigation-ready reports.\n\nThe solution should also support investigators in routing lawful disclosure or asset-freezing requests to the appropriate VASP through the SAHYOG Portal.",
    keyDeliverables: [
      "Automated identification of nearest VASP/exchange associated with unknown wallets",
      "API-driven blockchain tracing and attribution",
      "Multi-chain transaction analysis and visualization",
      "Identification of exchange clusters, hot wallets and deposit wallets",
      "Identification of mixers/tumblers, DeFi bridges and cross-chain swap services",
      "Automated VASP tagging with confidence scoring",
      "Wallet and transaction-flow risk classification",
      "Fund movement and cross-chain transaction visualization",
      "Identification of relevant laundering typologies",
      "SAHYOG Portal API integration",
      "Investigation-ready reports for LEAs",
      "Case-based analytics dashboard",
      "Support for lawful disclosure and asset-freezing request routing",
      "Scalable architecture for large-volume blockchain transaction analysis"
    ],
    sortOrder: 6
  },
  {
    slug: "real-time-crypto-fraud-attribution-system",
    title: "Real-Time Crypto Fraud Attribution System",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Financial Security / Blockchain / Law Enforcement",
    scope: "Cryptocurrency Fraud Investigation / VASP Attribution / Blockchain Intelligence / Multi-Chain Fraud Analysis",
    platformTech: "AI/ML, Agentic AI, Blockchain Analytics, Graph Analytics, Blockchain Indexing, Multi-Chain Analysis, Transaction Tracing, Pattern Recognition, Risk Scoring, API Integration, Data Visualization, Web Dashboard",
    description: "Develop a Real-Time Crypto Fraud Attribution System capable of automatically analyzing victim-reported cryptocurrency wallet addresses and identifying the nearest cryptocurrency exchange or Virtual Asset Service Provider (VASP) receiving direct deposits.\n\nThe system should ingest wallet addresses reported through cybercrime complaint systems, perform automated blockchain tracing, identify associated exchanges or VASPs, detect fund movement patterns, and generate actionable intelligence for investigators. It should support blockchain transaction graph analysis, exchange-wallet clustering, detection of intermediary laundering wallets, cross-chain fund movement analysis, and integration with SAHYOG and NCRP platforms.\n\nThe platform should provide real-time tracing, automated investigative recommendations, risk categorization, alerts and analytics dashboards for law enforcement agencies. It should support multiple blockchain ecosystems, scalable blockchain indexing, API integrations, AI/ML-assisted risk detection and automated recognition of fraud-related transaction patterns.",
    keyDeliverables: [
      "Real-time blockchain intelligence generation",
      "Automated VASP/exchange identification",
      "Automated tracing of suspect cryptocurrency wallets",
      "Blockchain transaction graph analysis",
      "Exchange-wallet clustering",
      "Detection of intermediary laundering wallets",
      "Cross-chain transaction and fund-flow analysis",
      "Fund-flow visualization",
      "Fraud-typology pattern recognition",
      "AI/ML-assisted wallet and transaction risk detection",
      "Automated alert generation and investigative recommendations",
      "SAHYOG and NCRP integration",
      "API-driven blockchain intelligence platform",
      "Scalable blockchain indexing architecture",
      "Law-enforcement analytics dashboard",
      "Standardized investigation reports",
      "Support for digital evidence collection and investigation workflows"
    ],
    sortOrder: 7
  },
  {
    slug: "real-time-identification-of-fraud-linked-cryptocurrency-exchanges",
    title: "Real-Time Identification of Fraud-Linked Cryptocurrency Exchanges from Victim-Reported Suspect Wallet Addresses through Automated Blockchain Analytics",
    organization: "Ministry of Home Affairs",
    department: "Indian Cyber Crime Coordination Centre (I4C), CIS Division",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Financial Security / Blockchain / Law Enforcement",
    scope: "Cryptocurrency Fraud Investigation / Blockchain Analytics / VASP Identification / Multi-Chain Transaction Analysis",
    platformTech: "AI/ML, Agentic AI, Blockchain Analytics, Graph Analytics, Blockchain Indexing, Multi-Chain Analysis, Transaction Tracing, Pattern Recognition, Risk Scoring, API Integration, Data Visualization, Web Dashboard",
    description: "Develop a Real-Time Crypto Fraud Attribution System to automatically analyze cryptocurrency wallet addresses reported by victims of cyber fraud and identify the nearest cryptocurrency exchange or Virtual Asset Service Provider (VASP) receiving direct deposits.\n\nThe system should ingest suspect wallet addresses from cybercrime complaint systems, perform automated blockchain tracing, identify associated exchanges or VASPs, detect fund movement patterns, and generate actionable intelligence for investigators. It should support transaction graph analysis, exchange-wallet clustering, detection of intermediary laundering wallets, cross-chain fund movement analysis, and integration with SAHYOG and NCRP platforms.\n\nThe platform should provide real-time tracing, automated investigative recommendations, risk categorization, alerts and analytics dashboards for law enforcement agencies. It should support multiple blockchain ecosystems, scalable blockchain indexing, API integrations, AI/ML-assisted risk detection and automated pattern recognition for fraud typologies.",
    keyDeliverables: [
      "Real-time blockchain intelligence generation",
      "Automated VASP/exchange identification",
      "Suspect wallet tracing and transaction analysis",
      "Blockchain transaction graph analysis",
      "Exchange-wallet clustering",
      "Detection of intermediary laundering wallets",
      "Cross-chain transaction and fund-flow analysis",
      "Fund-flow visualization",
      "AI/ML-assisted risk detection",
      "Automated fraud-typology pattern recognition",
      "Automated alerts and investigative recommendations",
      "SAHYOG and NCRP integration",
      "API-driven blockchain intelligence",
      "Scalable blockchain indexing",
      "Law-enforcement analytics dashboard",
      "Standardized investigation reports",
      "Digital evidence collection and investigation support"
    ],
    sortOrder: 8
  },
  {
    slug: "predictive-analytics-framework-for-cybercrime-complaints",
    title: "Development of a Predictive Analytics Framework for Cybercrime Complaints to Forecast Likely Cash Withdrawal Locations in Advance, Enabling Generation of Actionable Intelligence for Timely and Proactive Cybercrime Intervention",
    organization: "Ministry of Home Affairs",
    department: "Indian Cyber Crime Coordination Centre (I4C), CIS Division",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Financial Security / Law Enforcement",
    scope: "Cybercrime Prediction / Financial Fraud Analytics / Cash-Withdrawal Hotspot Prediction / Geospatial Risk Intelligence",
    platformTech: "AI/ML, Predictive Analytics, Geospatial Analytics, GIS, Pattern Detection, Risk Modelling, Real-Time Alerts, Data Visualization, Web Dashboard, API Integration",
    description: "Develop a predictive analytics framework for the National Cybercrime Reporting Portal to proactively forecast likely cash withdrawal locations associated with cybercrime and financial fraud. The framework should analyze historical cybercrime and financial data to identify potential withdrawal hotspots and generate actionable intelligence for law enforcement agencies at state and local levels, coordinated by I4C.\n\nThe intelligence should support proactive interventions such as deploying special teams or alerting local banks and ATMs in high-risk areas. It should also support banks and financial institutions through the Citizen Financial Cyber Fraud Reporting and Management System to enable faster fund blocking and improve recovery opportunities. The framework should enable real-time actionable intelligence sharing across jurisdictions between LEAs, banks/FIs and I4C.",
    keyDeliverables: [
      "AI/ML-based predictive analytics engine",
      "Analysis of historical cybercrime and financial data",
      "Prediction of potential cash-withdrawal hotspots",
      "Pattern detection and geospatial risk modelling",
      "Real-time risk and hotspot alerts",
      "GIS-enabled risk heatmap dashboard",
      "Drill-down filters by time, location and crime category",
      "Secure law-enforcement interface",
      "Investigator access to alerts, intelligence reports and evidence documentation",
      "Real-time notification system for LEAs, banks and I4C officers",
      "SMS, email, API and dashboard-based alert triggers",
      "Cross-jurisdiction actionable intelligence sharing"
    ],
    sortOrder: 9
  },
  {
    slug: "intelligent-border-video-analytics-platform-ibvap",
    title: "Intelligent Border Video Analytics Platform (IBVAP)",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Border Security / Defense / Surveillance Security",
    scope: "Intelligent Video Surveillance / Computer Vision / Border Monitoring / Real-Time Threat Detection",
    platformTech: "AI/ML, Computer Vision, Video Analytics, Object Detection, Object Tracking, Facial Recognition, ANPR, Intrusion Detection, Behavioral Analysis, Real-Time Video Processing, IP CCTV, Alert Management, Web Dashboard",
    description: "Develop an AI-driven software platform capable of transforming existing standard IP-based CCTV infrastructure into an intelligent surveillance network without requiring dedicated Facial Recognition Systems (FRS), Automatic Number Plate Recognition (ANPR), or smart-camera hardware.\n\nThe platform should ingest live video streams from existing CCTV cameras and perform real-time AI and computer vision-based analytics, including human detection and tracking, vehicle detection and classification, face detection, ANPR, virtual-fence intrusion detection, suspicious activity detection, night-time movement detection, real-time security alerts and event logging.\n\nThe solution should provide software-defined intelligent surveillance that reduces dependence on specialized hardware, improves situational awareness and response time, integrates with existing command and control systems, and remains cost-effective and scalable for deployment across remote border locations, Border Out Posts, check posts, border roads and other strategic installations.",
    keyDeliverables: [
      "AI-powered software-defined surveillance platform",
      "Integration with standard IP-based CCTV cameras",
      "Real-time human detection and tracking",
      "Vehicle detection and classification",
      "Face detection and facial recognition capability",
      "Automatic Number Plate Recognition (ANPR)",
      "Virtual-fence intrusion detection",
      "Suspicious activity detection",
      "Night-time movement detection",
      "Real-time security alerts",
      "Event logging and incident management",
      "AI-powered behavioral/video analytics",
      "Command-and-control system integration",
      "Surveillance dashboard for monitoring and analytics",
      "Scalable deployment architecture for remote locations",
      "Cost-effective software-based alternative to dedicated surveillance hardware"
    ],
    sortOrder: 10
  },
  {
    slug: "ai-based-intelligent-video-analytics-platform-for-border-surveillance",
    title: "AI-Based Intelligent Video Analytics Platform for Border Surveillance using Existing CCTV Infrastructure",
    organization: "Ministry of Home Affairs",
    department: "Sashastra Seema Bal (SSB), Police II Division",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Border Security / Defense / Surveillance Security",
    scope: "Intelligent Video Surveillance / Computer Vision / Border Monitoring / Real-Time Threat Detection",
    platformTech: "AI/ML, Computer Vision, Video Analytics, Object Detection, Object Tracking, Facial Recognition, ANPR, Intrusion Detection, Behavioral Analysis, Real-Time Video Processing, IP CCTV, Alert Management, Web Dashboard",
    description: "Develop an AI-driven software platform capable of transforming existing CCTV infrastructure at Border Out Posts (BOPs), check posts, border roads and other strategic locations into an intelligent surveillance network without requiring dedicated Facial Recognition Systems (FRS), Automatic Number Plate Recognition (ANPR) or smart-camera hardware.\n\nThe platform should ingest live video streams from standard IP-based CCTV cameras and perform real-time AI and Computer Vision-based video analytics. Required capabilities include human detection and tracking, vehicle detection and classification, face detection, ANPR, virtual-fence intrusion detection, suspicious activity detection, night-time movement detection, real-time alert generation and event logging.\n\nThe solution should provide software-defined intelligent surveillance, reduce dependence on expensive specialized hardware, improve situational awareness and response time, integrate with existing command and control systems, and support cost-effective and scalable deployment across remote border locations and strategic installations.",
    keyDeliverables: [
      "AI-powered software-defined surveillance platform",
      "Integration with existing standard IP-based CCTV cameras",
      "Real-time human detection and tracking",
      "Vehicle detection and classification",
      "Face detection and facial recognition",
      "Automatic Number Plate Recognition (ANPR)",
      "Virtual-fence intrusion detection",
      "Suspicious activity detection",
      "Night-time movement detection",
      "Real-time security alerts and event logging",
      "AI-powered video and behavioral analytics",
      "Integration with existing command and control systems",
      "Surveillance monitoring and analytics dashboard",
      "Scalable architecture for remote border deployments",
      "Cost-effective software-based surveillance solution"
    ],
    sortOrder: 11
  },
  {
    slug: "ai-based-fake-identity-and-document-screening-system",
    title: "AI-Based Fake Identity & Document Screening System",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Border Security / Identity Security / Document Verification",
    scope: "Identity Verification / Document Fraud Detection / Forgery Detection / Border Checkpoint Security",
    platformTech: "AI/ML, OCR, Computer Vision, Document Analysis, Image Forensics, Face Verification, Tampering Detection, Metadata Analysis, Risk Scoring, Database Validation, Web Dashboard",
    description: "Develop an AI-powered document screening platform for border checkpoints to automatically analyze passports, visas, national identity cards, driving licenses, permits and other travel documents. The system should address challenges such as fake or altered documents, modified personal information, tampered visa stamps, identity impersonation, multiple identities and expired or blacklisted travel documents.\n\nThe platform should reduce dependence on manual inspection by extracting information from identity documents using OCR, validating the extracted information against official document standards and rules, detecting digitally or physically altered documents, and verifying whether the person presenting the document matches the document owner.\n\nThe solution should include OCR extraction, document validation, AI-based tampering detection and face verification, and generate a risk assessment to assist border security personnel with faster and more consistent screening decisions.",
    keyDeliverables: [
      "OCR-based identity and travel document information extraction",
      "Support for passport, visa, national ID, driving licence and permit documents",
      "Extraction of passport name, number, nationality, date of birth, expiry date and gender",
      "Visa number, visa type, entry validation and stay-duration extraction",
      "Document validation against official document standards",
      "Detection of photo replacement",
      "Detection of text manipulation",
      "Visa/stamp forgery detection",
      "Image metadata analysis",
      "Face detection and document-owner verification",
      "Risk assessment for suspicious documents",
      "Faster automated document screening",
      "Digital trail for investigation and intelligence analysis",
      "Screening interface/dashboard for border security personnel"
    ],
    sortOrder: 12
  },
  {
    slug: "ai-powered-criminal-network-and-relationship-analysis-system",
    title: "AI-Powered Criminal Network & Relationship Analysis System",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Law Enforcement / Public Safety / Criminal Intelligence",
    scope: "Criminal Network Analysis / Relationship Discovery / Intelligence Analysis / Graph Analytics",
    platformTech: "AI/ML, NLP, Graph Analytics, Entity Extraction, Relationship Mapping, Pattern Detection, Data Integration, Data Visualization, Network Analysis, Web Dashboard",
    description: "Develop an AI-powered system capable of analyzing large volumes of structured and unstructured criminal and intelligence-related data to uncover hidden relationships and networks among individuals, organizations, locations and events.\n\nThe system should collect and process data from multiple sources such as FIRs and police reports, Call Detail Records (CDRs), financial transactions, surveillance reports, social media intelligence, criminal history databases and intelligence reports. It should extract important entities including people, locations, vehicles, phone numbers and organizations, and build relationship maps showing connections between them.\n\nThe platform should identify key individuals who play influential roles within criminal networks, detect suspicious patterns and unusual activities, and provide visual and analytical insights that assist investigators in understanding criminal networks and generating actionable intelligence.",
    keyDeliverables: [
      "Multi-source criminal and intelligence data ingestion",
      "Structured and unstructured data processing",
      "Entity extraction for people, locations, vehicles, phone numbers and organizations",
      "Automated relationship and connection discovery",
      "Criminal network graph generation",
      "Identification of key/influential individuals within networks",
      "Suspicious-pattern and unusual-activity detection",
      "Graph-based relationship visualization",
      "AI/ML and NLP-based intelligence analysis",
      "Investigator-focused analytics dashboard",
      "Visual and analytical investigation insights",
      "Actionable intelligence generation for investigators"
    ],
    sortOrder: 13
  },
  {
    slug: "secure-digital-document-management-system-for-legal-and-investigation-records",
    title: "Secure Digital Document Management System for Legal and Investigation Records",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Law Enforcement / Legal Technology / Information Security",
    scope: "Digital Document Management / Legal Records / Investigation Records / Document Security / Evidence Integrity",
    platformTech: "Web Development, Cloud Computing, AI, Blockchain, Digital Signatures, Secure Access Control, Document Management, Search & Retrieval, Audit Trails, Version Control, Data Security",
    description: "Develop a Secure Digital Document Management System (DMS) for law enforcement agencies, legal institutions and investigative departments to securely store, organize, manage, retrieve and share sensitive legal and investigation documents.\n\nThe system should support documents such as FIRs and police reports, investigation records, witness statements, charge sheets, court filings, evidence records, forensic reports, legal notices and judgments. It should digitize and centralize document storage, ensure secure access and confidentiality, prevent unauthorized modifications, maintain a complete audit trail, provide efficient document search and retrieval, support collaboration among authorized stakeholders, and help meet legal and regulatory requirements.\n\nThe platform should be secure, scalable and intelligent while preserving document integrity, confidentiality, legal validity and evidentiary integrity. The source also mentions technologies including Cloud Computing, Artificial Intelligence, Blockchain, Digital Signatures and Secure Access Control.",
    keyDeliverables: [
      "Secure centralized digital document repository",
      "Digitization and organization of legal and investigation documents",
      "Role-based secure access and confidentiality controls",
      "Protection against unauthorized document modification",
      "Document version control",
      "Complete audit trail of document activities",
      "Search and retrieval functionality",
      "Secure document sharing and collaboration",
      "Digital signatures and document integrity mechanisms",
      "Evidence and document integrity management",
      "Compliance and audit tracking",
      "Scalable document management platform",
      "AI-assisted document management capabilities",
      "Blockchain-based integrity support where applicable"
    ],
    sortOrder: 14
  },
  {
    slug: "student-innovation-decentralized-and-distributed-ledger-technology",
    title: "Student Innovation: Decentralized and Distributed Ledger Technology for Digital Information",
    organization: "AICTE",
    department: "AICTE, MIC-Student Innovation",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Blockchain / Digital Technology",
    scope: "Blockchain Innovation / Distributed Ledger Technology / Digital Information Management",
    platformTech: "Blockchain, Distributed Ledger Technology (DLT), Web Development, Smart Contracts, Digital Assets, Decentralized Applications",
    description: "Provide innovative ideas based on decentralized and distributed ledger technology used to store digital information. The technology powers cryptocurrencies and NFTs and has the potential to bring significant changes across multiple sectors.",
    keyDeliverables: [
      "Innovative blockchain-based solution concept",
      "Application of decentralized and distributed ledger technology",
      "Secure storage and management of digital information",
      "Demonstration of blockchain-based use cases",
      "Potential application across different sectors",
      "Prototype or proof of concept demonstrating the proposed innovation",
      "Documentation explaining the solution and its use case"
    ],
    sortOrder: 15
  },
  {
    slug: "model-agnostic-computer-vision-assurance-framework",
    title: "Model-Agnostic Computer Vision Assurance and Integrity Assessment Framework",
    organization: "",
    department: "",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Artificial Intelligence / Computer Vision Security",
    scope: "Computer Vision Assurance / Training Data Integrity / Model Integrity / Inference Provenance / AI Security",
    platformTech: "AI/ML, Computer Vision, Data Integrity, Model Security, Backdoor Detection, Anomaly Detection, Distribution-Shift Detection, Cryptographic Hashing, Digital Signatures, Provenance Tracking, Audit Logging, ONNX, PyTorch/TorchScript, COCO, YOLO",
    description: "Develop an extensible, model-agnostic computer-vision assurance framework capable of evaluating the integrity and security of contributed training datasets, trained models and inference records. The system should provide evidence-based assessments without assuming that every contributing data or model source is trusted.\n\nThe solution should identify suspicious training-data behaviour including trigger injection, label flipping, systematic mislabelling, near-duplicate flooding and out-of-distribution insertion, while aggregating available contributor, batch or source metadata into source-level risk assessments. It should assess model integrity for anomalous, substituted or backdoor-like behaviour using appropriate techniques based on the available access level, while clearly reporting assumptions, confidence and limitations.\n\nThe platform should create verifiable cryptographic provenance linking input images, model identifiers or weight digests, preprocessing and inference configurations, and generated outputs. It should make post-hoc alteration, substitution or replay of protected inference records detectable using hashes, signatures and suitable sequence, timestamp or nonce controls.\n\nThe framework should also detect distribution shifts caused by terrain, season, sensor, illumination or acquisition conditions, distinguish operational drift from suspicious manipulation where evidence permits, and provide calibrated risk or confidence scores. Every finding should include a human-readable reason, supporting evidence, confidence or severity, affected asset and recommended disposition such as accept, review or quarantine.\n\nThe complete evaluation workflow must operate offline in an air-gapped environment, support common dataset formats such as COCO and YOLO and organiser-defined model formats including ONNX and PyTorch/TorchScript. White-box assessment methods should gracefully fall back or clearly report unavailable assessments when only black-box access is provided.",
    keyDeliverables: [
      "Model-agnostic computer-vision assurance framework",
      "Training-data integrity assessment",
      "Detection of trigger injection and backdoor-related data",
      "Detection of label flipping and systematic mislabelling",
      "Near-duplicate and out-of-distribution sample detection",
      "Contributor/source-level risk assessment",
      "Model integrity and substitution assessment",
      "Backdoor-like behaviour analysis",
      "Behavioural fingerprinting and reference-battery comparison",
      "Inference provenance and cryptographic integrity protection",
      "Detection of inference-record alteration, substitution and replay",
      "Distribution-shift and anomaly assessment",
      "Calibrated risk/confidence scoring",
      "Human-readable evidence for every finding",
      "Analyst dashboard with accept, review and quarantine recommendations",
      "Tamper-evident audit trail",
      "Offline and air-gapped deployment",
      "Support for COCO, YOLO, ONNX and PyTorch/TorchScript formats",
      "Reproducible poisoning, backdoor, substitution and tampering test scenarios",
      "Assurance-report schema",
      "Reproducible audit log",
      "Architecture and setup documentation",
      "Coverage statement identifying supported attack classes, assumptions and limitations"
    ],
    sortOrder: 16
  },
  {
    slug: "trustworthy-computer-vision-integrity-assurance",
    title: "Trustworthy Computer Vision Integrity Assurance for Data, Models and Inference Outputs in Multi-Contributor Pipelines",
    organization: "Ministry of Defence (MoD)",
    department: "Indian Army (DGIS)",
    targetDomain: "Agentic AI",
    difficulty: "Advanced",
    industry: "Cybersecurity / Artificial Intelligence / Defence Technology",
    scope: "Computer Vision Assurance / AI Model Integrity / Training Data Integrity / Inference Provenance / AI Security",
    platformTech: "AI/ML, Computer Vision, Data Integrity, Model Security, Backdoor Detection, Anomaly Detection, Distribution-Shift Detection, Cryptographic Hashing, Digital Signatures, Provenance Tracking, Audit Logging, ONNX, PyTorch/TorchScript, COCO, YOLO",
    description: "Develop an extensible, model-agnostic computer-vision assurance framework capable of evaluating the integrity and security of contributed training datasets, trained models and inference records in multi-contributor pipelines.\n\nThe system should identify suspicious training-data behaviour including trigger injection, label flipping, systematic mislabelling, near-duplicate flooding and out-of-distribution insertion. Where contributor, batch or source metadata is available, the system should aggregate sample-level evidence into source-level risk assessments.\n\nThe framework should assess supplied models for anomalous, substituted or backdoor-like behaviour using techniques appropriate to the available access level, while clearly reporting assumptions, confidence and limitations. It should also establish verifiable cryptographic provenance between input images, model identifiers or weight digests, preprocessing and inference configurations, and resulting outputs, making post-hoc alteration, substitution or replay detectable.\n\nThe solution should detect material distribution shifts caused by terrain, season, sensor, illumination or acquisition conditions, provide calibrated risk/confidence scores, and distinguish probable operational drift from suspicious manipulation where supported by evidence.\n\nEvery finding should provide a human-readable reason, supporting evidence, confidence or severity, affected asset and recommended action such as accept, review or quarantine. The complete workflow must operate offline in an air-gapped environment and support COCO, YOLO, ONNX and PyTorch/TorchScript formats. White-box methods should gracefully fall back or report when the required access is unavailable.",
    keyDeliverables: [
      "Model-agnostic computer-vision assurance framework",
      "Training-data integrity assessment",
      "Detection of trigger injection and backdoor-related data",
      "Label-flipping and systematic-mislabelling detection",
      "Near-duplicate and out-of-distribution sample detection",
      "Contributor/source-level risk assessment",
      "Model integrity and substitution assessment",
      "Backdoor-like behaviour analysis",
      "Behavioural fingerprinting and reference-battery comparison",
      "Cryptographic inference provenance",
      "Detection of inference-record alteration, substitution and replay",
      "Distribution-shift and anomaly assessment",
      "Calibrated risk/confidence scoring",
      "Human-readable evidence for every finding",
      "Analyst-facing assurance dashboard",
      "Accept/review/quarantine recommendations",
      "Tamper-evident audit trail",
      "Offline and air-gapped deployment",
      "COCO and YOLO dataset support",
      "ONNX and PyTorch/TorchScript model support",
      "Reproducible poisoning, backdoor, substitution and tampering test scenarios",
      "Assurance-report schema",
      "Reproducible audit log",
      "Source code, architecture and setup documentation",
      "Coverage statement identifying supported attack classes, assumptions and limitations"
    ],
    sortOrder: 17
  }
];

import { restoreRecoveredProblemStatements } from "./restoreRecoveredProblemStatements.js";

export async function seedProblemStatements() {
  try {
    // Drop legacy id_1 index if it exists in MongoDB
    try {
      await ProblemStatement.collection.dropIndex("id_1");
    } catch (_e) {
      // index might not exist, ignore
    }

    for (const item of problemStatementsData) {
      await ProblemStatement.findOneAndUpdate(
        { slug: item.slug },
        { $set: item },
        { upsert: true, new: true }
      );
    }
    console.log(`[seed] Successfully seeded ${problemStatementsData.length} problem statements.`);

    await restoreRecoveredProblemStatements();
  } catch (err) {
    console.error("[seed-problem-statements] Failed:", err instanceof Error ? err.message : err);
  }
}
